Project-GPIT-Payroll/PayrollWeb/Controllers/DataSyncController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Web;
using System.Web.Mvc;
using PayrollWeb.Models;

namespace PayrollWeb.Controllers
{
    public class DataSyncController : Controller
    {
        //
        // GET: /DataSync/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /DataSync/Details/5

        public ActionResult SyncData()
        {
            //var dataImport= new OracleDataImportManger();
            //var importedData = dataImport.GetEmployees();
            //var result = dataImport.SaveData(importedData);
            return Json(new { ProcessResult = 1}, JsonRequestBehavior.AllowGet);
        }

        // GET: /DataSync/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /DataSync/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /DataSync/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /DataSync/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /DataSync/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /DataSync/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Project-GPIT-Payroll/PayrollWeb/Views/DataSync/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}


@section PageBanner
{
    Import Employee Data and Sync
}
@section PageSpecificJsHeader
{   
    <link type="text/css" rel="stylesheet" href="~/Content/themes/base/jquery.ui.core.css"/>
    <link type="text/css" rel="stylesheet" href="~/Content/themes/base/jquery.ui.all.css"/>
    <link type="text/css" rel="stylesheet" href="~/Content/DataTables-1.9.4/media/css/jquery.dataTables.css"/>
    <link type="text/css" rel="stylesheet" href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools.css"/>
    <link type="text/css" rel="stylesheet" href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools_JUI.css"/>
    <link type="text/css" rel="stylesheet" href="~/Scripts/DataTables-1.9.4/jquery.dataTables.bootstrap.css"/>
}
@section PageSpecificJs
{
    <script type="text/javascript">
        $(function() {
            $('#btnSync').on("click", function (e) {
                e.preventDefault();
                $('#prel').show();
                $('#btnSync').text('Processing. Please wait...');
                $('#btnSync').attr("disabled", "disabled");
                
                $.get('@Url.Action("SyncData","DataSync")', function (rdata) {
                    $('#prel').hide();
                    $('#btnSync').text('Sync Data Now');
                    $('#btnSync').removeAttr("disabled");
                    if (rdata.ProcessResult.HasError == true) {
                        var lst = $('<ul>');
                        var msgFail = $('<p>', { text: "Following employee data could not be processed." }).append('<br/>');
                        $('#dvProcessResult').append(msgFail);
                        for (var i = 0; i < rdata.ProcessResult.Messages.length; i++) {
                            var el = $('<li>', { text: rdata.ProcessResult.Messages[i] });
                            lst.append(el);
                        }
                        $('#dvProcessResult').append(lst);
                    } else {
                        var msgSuc = $('<p>', { text: "Data import and sync process completed successfully." }).append('<br/>');
                        $('#dvProcessResult').append(msgSuc);
                    }

                });
            });
        });
        
    </script>
}
<div class="row-fluid">
    <div class="form-actions"><i id="prel" style="display: none;"><img src="~/Content/pleasewait.gif"/></i>
        <button  id="btnSync" type="@*submit*@" class="btn btn-primary">Sync Data Now</button>
    </div>
    <div id="dvProcessResult"></div>
</div>