Project-GPIT-Payroll/PayrollWeb/ViewModels/BonusProcess.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayrollWeb.Utility;

namespace PayrollWeb.ViewModels
{
    public class BonusProcess
    {
        public BonusProcess()
        {
            //prl_bonus_process_detail = new BonusProcessDetail();
            prl_bonus_name = new BonusName();
            prl_department = new Department();
            prl_division = new Division();
            prl_religion = new Religion();
            prl_grade = new Grade();
            prl_company = new Company();
            prl_fiscal_year = new FiscalYr();
        }

       // public virtual BonusProcessDetail prl_bonus_process_detail { get; set; }
        public virtual BonusName prl_bonus_name { get; set; }
        public virtual Department prl_department { get; set; }
        public virtual Division prl_division { get; set; }
        public virtual Religion prl_religion { get; set; }
        public virtual Grade prl_grade { get; set; }
        public virtual Company prl_company { get; set; }
        public virtual FiscalYr prl_fiscal_year { get; set; }


        [HiddenInput(DisplayValue = true)]
        public int id { get; set; }

        [Required(ErrorMessage = "Can not be null or empty.")]
        [DisplayName("Bonus Name")]
        public int bonus_name_id { get; set; }

        [Required(ErrorMessage = "Can not be null or empty.")]
        [DisplayName("Fiscal Year")]
        public int fiscal_year_id { get; set; }

        [Required(ErrorMessage = "Can not be null or empty.")]
        [DisplayName("Month")]
        public string month { get; set; }

        [Required(ErrorMessage = "Can not be null or empty.")]
        [DisplayName("Year")]
        public string year { get; set; }

        [DisplayName("Batch No.")]
        public string batch_no { get; set; }

        [Required(ErrorMessage = "Can not be null or empty.")]
        [DisplayName("Process Date")]
        public Nullable<System.DateTime> process_date { get; set; }

        [Required(ErrorMessage = "Can not be null or empty.")]
        [DisplayName("Festival Date")]
        public Nullable<System.DateTime> festival_date { get; set; }

        [Required(ErrorMessage = "Can not be null or empty.")]
        [DisplayName("Relegion")]
        public int religion_id { get; set; }

        [DisplayName("Company")]
        public int company_id { get; set; }

        [DisplayName("Grade")]
        public int grade_id { get; set; }

        [DisplayName("Division")]
        public int division_id { get; set; }

        [DisplayName("Department")]
        public int department_id { get; set; }

        [DisplayName("Gender")]
        public string gender { get; set; }

        [DisplayName("Pay with Next Salary")]
        public string is_pay_with_salary { get; set; }

        public string is_available_in_payslip { get; set; }
        
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}

Project-GPIT-Payroll/PayrollWeb/ViewModels/BonusUploadView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using PayrollWeb.Utility;

namespace PayrollWeb.ViewModels
{
    public class BonusUploadView
    {
        [Required(ErrorMessage = "Fiscal year can not be null.")]
        public int FiscalYear { get; set; }

        [Required(ErrorMessage = "Month can not be null.")]
        public string MonthYear { get; set; }

        [Required(ErrorMessage = "Year can not be null.")]
        public int Year { get; set; }

        [Required(ErrorMessage = "Name can not be null.")]
        public int BonusName { get; set; }

        public List<BonusName> BonusNames { get; set; }

        public Dictionary<string, int> GetMonths()
        {
            return DateUtility.GetMonths();
        }

        public List<int> GetYears()
        {
            return DateUtility.GetYears();
        }
    }
}

Project-GPIT-Payroll/PayrollWeb/Controllers/BonusController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using com.gpit.DataContext;
using AutoMapper;
using com.gpit.Model;
using Newtonsoft.Json.Serialization;
using OfficeOpenXml;
using PagedList;
using PayrollWeb.CustomSecurity;
using PayrollWeb.Service;
using PayrollWeb.ViewModels;
using PayrollWeb.Utility;
using System.Web.Security;

namespace PayrollWeb.Controllers
{
    public class BonusController : Controller
    {
        private readonly payroll_systemContext dataContext;
        //
        // GET: /Bonus/

        public BonusController(payroll_systemContext cont)
        {
            this.dataContext = cont;
        }

        
        public ActionResult BonusMain(string menuName)
        {
            return View();
        }

        [PayrollAuthorize]
        public ActionResult Index()
        {
            var _bonus = dataContext.prl_bonus_name.ToList();
            return View(Mapper.Map<List<BonusName>>(_bonus));
        }

        //
        // GET: /Bonus/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        [PayrollAuthorize]
        public ActionResult Create()
        {

            var _bonus = new BonusName();
            return View(_bonus);
        }

        [PayrollAuthorize]
        [HttpPost]
        public ActionResult Create(BonusName item)
        {
            var res = new OperationResult();
            try
            {
                var _bonus = Mapper.Map<prl_bonus_name>(item);
                dataContext.prl_bonus_name.Add(_bonus);
                dataContext.SaveChanges();

                res.IsSuccessful = true;
                res.Message = _bonus.name + " created. ";
                TempData.Add("msg", res);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [PayrollAuthorize]
        public ActionResult Edit(int id)
        {
            

            var _bonus = dataContext.prl_bonus_name.SingleOrDefault(x => x.id == id);
            return View(Mapper.Map<BonusName>(_bonus));
        }

        //
        // POST: /Bonus/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, BonusName item)
        {
            var res = new OperationResult();
            try
            {
                var _bonus = dataContext.prl_bonus_name.SingleOrDefault(x => x.id == item.id);
                _bonus.name = item.name;
                dataContext.SaveChanges();

                res.IsSuccessful = true;
                res.Message = _bonus.name + " edited. ";
                TempData.Add("msg", res);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [PayrollAuthorize]
        public ActionResult Delete(int id)
        {
            string name = "";
            var res = new OperationResult();
            try
            {
                var _bonus = dataContext.prl_bonus_name.SingleOrDefault(x => x.id == id);
                if (_bonus == null)
                {
                    return HttpNotFound();
                }
                name = _bonus.name;
                dataContext.prl_bonus_name.Remove(_bonus);
                dataContext.SaveChanges();

                res.IsSuccessful = true;
                res.Message = name + " deleted.";
                TempData.Add("msg", res);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                res.IsSuccessful = false;
                res.Message = name + " could not delete.";
                TempData.Add("msg", res);
                return RedirectToAction("Index");
            }
        }

        //
        // POST: /Bonus/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [PayrollAuthorize]
        public ActionResult ConfigureBonus(int bonusId = 0)
        {
            

            ViewBag.SelectedIndex = bonusId;
            var prlGrds = dataContext.prl_grade.ToList();
            var grades = Mapper.Map<List<Grade>>(prlGrds);
            BonusConfiguration bonusConfig;
            if (bonusId == 0)
                bonusConfig = new BonusConfiguration();
            else
            {
                var dbVal = dataContext.prl_bonus_configuration.SingleOrDefault(x => x.bonus_name_id == bonusId);
                if (dbVal == null)
                {
                    dbVal = new prl_bonus_configuration();
                }
                bonusConfig = Mapper.Map<BonusConfiguration>(dbVal);
                bonusConfig.bonus_name_id = bonusId;
                if (dbVal.bonus_name_id > 0)
                {
                    var ids = dbVal.prl_bonus_name.prl_grade.Select(x => x.id);
                    foreach (var g in grades)
                    {
                        if (ids.Contains(g.id))
                            g.IsSelected = true;
                    }
                }
            }

            bonusConfig.Grades = grades;

            var prlBonusNames = dataContext.prl_bonus_name.ToList();
            ViewBag.BonusNames = Mapper.Map<List<BonusName>>(prlBonusNames);
            return View(bonusConfig);
        }

        [HttpPost]
        public ActionResult ConfigureBonus(BonusConfiguration bc)
        {
            bool errorFound = false;
            var operationResult = new OperationResult();

            try
            {
                if (ModelState.IsValid)
                {
                    //check to see if grade is selected
                    var lstOfGrades = new List<prl_grade>();

                    if (bc.is_festival == "SELECT")
                    {
                        errorFound = true;
                        ModelState.AddModelError("is_festival", "Please Select.");
                    }
                    if (!bc.Grades.Any(x => x.IsSelected == true))
                    {
                        errorFound = true;
                        ModelState.AddModelError("Grades", "No grade(s) selected.");
                    }

                    if (bc.flat_amount == null && bc.percentage_of_basic == null)
                    {
                        errorFound = true;
                        ModelState.AddModelError("", "Enter flat or percentage amount.");
                    }
                    if (bc.flat_amount <= 0 || bc.percentage_of_basic <= 0)
                    {
                        errorFound = true;
                        ModelState.AddModelError("", "Flat or percentage amount should be greater than zero.");
                    }
                    if (!errorFound)
                    {
                        bc.Grades = bc.Grades.Where(x => x.IsSelected == true);
                        var ids = bc.Grades.Select(x => x.id).ToList();
                        lstOfGrades = dataContext.prl_grade.AsEnumerable().Where(x => ids.Contains(x.id)).ToList();
                    }
                    if (!errorFound)
                    {
                        var prlConf = Mapper.Map<prl_bonus_configuration>(bc);
                        prlConf.prl_bonus_name = dataContext.prl_bonus_name.SingleOrDefault(x => x.id == bc.bonus_name_id);
                        if (prlConf.prl_bonus_name != null)
                        {
                            prlConf.prl_bonus_name.prl_grade.Clear();
                            prlConf.prl_bonus_name.prl_grade = lstOfGrades;
                        }
                        else
                        {
                            prlConf.prl_bonus_name.prl_grade = new Collection<prl_grade>();
                            prlConf.prl_bonus_name.prl_grade = lstOfGrades;
                        }

                        BonusService bns = new BonusService(dataContext);
                        operationResult.IsSuccessful = bns.CreateConfiguration(prlConf);
                        operationResult.Message = "Bonus Configuration saved successfully.";
                    }

                    if (!errorFound && operationResult.IsSuccessful)
                    {
                        operationResult.IsSuccessful = true;
                        operationResult.Message = "Configuration saved.";
                        TempData.Add("msg", operationResult);
                        return RedirectToAction("ConfigureBonus");
                    }
                }
            }
            catch (Exception ex)
            {
                operationResult.IsSuccessful = false;
                operationResult.Message = ex.InnerException != null ? ex.InnerException.Message : ex.Message;
                TempData.Add("msg", operationResult);
            }

            

            var prlBonusNames = dataContext.prl_bonus_name.ToList();
            ViewBag.BonusNames = Mapper.Map<List<BonusName>>(prlBonusNames);
            return View(bc);
        }

        public JsonResult GetEmployeeSeach(string query)
        {
            var lst = dataContext.prl_employee.AsEnumerable()
                .Where(x => x.name.ToLower().Contains(query.ToLower()) || x.emp_no.Contains(query))
                .Select(x => new SearchEmployeeData() { id = x.id, name = x.name }).ToList();
            return Json(lst, JsonRequestBehavior.AllowGet);
        }

        [PayrollAuthorize]
        public ActionResult HoldBonus(int bonusId = 0)
        {

Project-GPIT-Payroll/PayrollWeb/Views/Bonus/BonusProcess.cshtml
@using System.Diagnostics.Eventing.Reader
@using PayrollWeb.Models
@using PayrollWeb.ViewModels
@model PayrollWeb.ViewModels.BonusProcess

@{
    ViewBag.Title = "BonusProcess";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}

@section PageBanner
{
    Bonus Process
}


<br style="clear: both;"/>
    @{
        if (TempData.ContainsKey("msg"))
        {
            var res = (OperationResult)TempData["msg"];
            if (res.IsSuccessful)
            {
                <div id="notifyUser" class="alert alert-success">
			    <button data-dismiss="alert" class="close" type="button">×</button>
			    <div>@res.Message </div>
                </div>    
            }
            else
            {
                <div id="notifyUser" class="alert alert-error">
			    <button data-dismiss="alert" class="close" type="button">×</button>
			    <div>@res.Message </div>
                </div> 
            }
        }
    }

@using (Html.BeginForm("BonusProcess","Bonus",FormMethod.Post,new{@class="form-inline"})) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.id)
    
        <table class="table" style="border:none;">
        <tr style="border:none;">
            <td>
                @Html.LabelFor(model => model.bonus_name_id)
            </td>
            <td>
               @Html.DropDownListFor(model => model.bonus_name_id, new SelectList(@ViewBag.BonusNames, "id", "name"), "---- Select ----")<br />
               @Html.ValidationMessageFor(model => model.bonus_name_id) 
            </td>
            <td style="width: 10px;"></td>
            <td>
                
            </td>
            <td>
                
                
            </td>
            
        </tr>
        <tr style="border:none;">
            <td>
                @Html.LabelFor(model => model.religion_id)
            </td>
            <td >
                @Html.DropDownListFor(model => model.religion_id, new SelectList(@ViewBag.Religions, "id", "name"), "---- ALL ----")<br />
            </td>
            
        </tr>
        <tr style="border:none;">
            <td> @Html.LabelFor(model=>model.process_date)</td>
            <td colspan="4">
                @Html.EditorFor(model => model.process_date)<br />
                @Html.ValidationMessageFor(model => model.process_date)
            </td>
        </tr>
        <tr style="border:none;">
            <td> @Html.LabelFor(model=>model.festival_date)</td>
            <td colspan="4">
                @Html.EditorFor(model => model.festival_date)<br />
                @Html.ValidationMessageFor(model => model.festival_date)
            </td>
        </tr>
        <tr style="border:none;">
            <td> @Html.LabelFor(model=>model.is_pay_with_salary)</td>
            <td colspan="4">
                @Html.DropDownListFor(model=>model.is_pay_with_salary,new SelectList(EnumToSelectItemList.GetEnumSelectList<IsPayWithSalary>(),"Text","Text"))
            </td>
        </tr>
        <tr style="border:none;">
            <td>

            </td>
            <td style="float:right; border:none;">
                 @*<p>
                    <input class="btn btn-primary" type="submit" value="Process" onclick = "BonusProcess(this); return false;" />
                   </p>*@
                <i id="prel" style="display: none;"><img src="~/Content/pleasewait.gif"/></i>
                <button id="btnProcess" type="button" class="btn btn-primary" onclick = "BonusProcess(this); return false;">Process</button>
            </td>
        </tr>
        <tr >
            <td style="color:gray; font-size:22px;">
                Non mandatory options
            </td>
            <td colspan="4"></td>
        </tr>
        <tr style="border:none;">
            <td>
                @Html.LabelFor(model => model.division_id) 
            </td>
            <td >
                @Html.DropDownListFor(model => model.division_id, new SelectList(@ViewBag.DivisionNames, "id", "name"), "---- ALL ----")<br />
            </td>
            <td style="width: 10px;"></td>
            <td>
                @Html.LabelFor(model => model.department_id)
            </td>
            <td>
                @Html.DropDownListFor(model => model.department_id, new SelectList(@ViewBag.DeptNames, "id", "name"), "---- ALL ----")<br />
            </td>
        </tr>
        <tr style="border:none;">
            <td>
                @Html.LabelFor(model => model.grade_id)
            </td>
            <td>
                @Html.DropDownListFor(model => model.grade_id, new SelectList(@ViewBag.Grades, "id", "grade"), "---- ALL ----")<br />
            </td>
            <td style="width: 10px;"></td>
            <td> @Html.LabelFor(model=>model.gender)</td>
            <td colspan="4">
                @Html.DropDownListFor(model=>model.gender,new SelectList(EnumToSelectItemList.GetEnumSelectList<Genders>(),"Text","Text"))
            </td>
        </tr>
    </table>
    
    
   
}

<div id="prcsBonus" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-body">
    <p>Are you sure you want to process bonus?</p>
    </div>
    <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button id="btnPrcsBonus" class="btn btn-primary">Process</button>
    </div>
</div>

@section PageSpecificJs
{

    <script type="text/javascript" src="~/Scripts/bootstrap-datepicker.js"></script>
    <script type="text/javascript">
        $('#process_date,#festival_date').datepicker({ dateFormat: 'yy-mm-dd' });
    </script>

    <script type="text/javascript">
        function BonusProcess(el) {
            $('#prcsBonus').modal('show');

            $('#btnPrcsBonus').click(function () {
                $('#prcsBonus').modal('hide');
                var test = $(el).attr('href');
                document.forms[0].submit();
            });
        }

        function ShowBusy() {
            $('#prel').show();
            $('#btnProcess').text('Processing. Please wait...');
            $('#btnProcess').attr("disabled", "disabled");
        }
        function HideBusy() {
            $('#prel').hide();
            $('#btnProcess').text('Process');
            $('#btnProcess').removeAttr("disabled");
        }
    </script>

}

Project-GPIT-Payroll/PayrollWeb/Views/Bonus/ConfigureBonus.cshtml
@using System.Diagnostics.Eventing.Reader
@using PayrollWeb.Models
@using PayrollWeb.ViewModels
@model PayrollWeb.ViewModels.BonusConfiguration

@{
    ViewBag.Title = "ConfigureBonus";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}

@section PageBanner
{
   Bonus Configuration
}


<br style="clear: both;"/>
    @{
        if (TempData.ContainsKey("msg"))
        {
            var res = (OperationResult)TempData["msg"];
            if (res.IsSuccessful)
            {
                <div id="notifyUser" class="alert alert-success">
			    <button data-dismiss="alert" class="close" type="button">×</button>
			    <div>@res.Message </div>
                </div>    
            }
            else
            {
                <div id="notifyUser" class="alert alert-error">
			    <button data-dismiss="alert" class="close" type="button">×</button>
			    <div>@res.Message </div>
                </div> 
            }
        }
    }

@using (Html.BeginForm("ConfigureBonus", "Bonus", FormMethod.Post, new { @class = "form-inline" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.id)
    
        <table class="table">
        <tr>
            <td >   
                @Html.LabelFor(model => model.bonus_name_id)
            </td>
            <td>
               @Html.DropDownListFor(model => model.bonus_name_id, new SelectList(@ViewBag.BonusNames, "id", "name", @ViewBag.SelectedIndex), "---- Select ----")<br />
               @Html.ValidationMessageFor(model => model.bonus_name_id) 
            </td>
            <td style="width: 10px;"></td>
            <td >
                @Html.LabelFor(model => model.effective_from)
            </td>
            <td>
                @Html.EditorFor(model => model.effective_from)
                @Html.ValidationMessageFor(model => model.effective_from)
            </td>
        </tr>
        <tr>
            <td> 
                @Html.LabelFor(model => model.is_festival)
                
            </td>
            <td >
                @Html.DropDownListFor(model => model.is_festival, new SelectList(EnumToSelectItemList.GetEnumSelectList<IsFestival>(), "Text", "Text"))
                @Html.ValidationMessageFor(model => model.is_festival)
            </td>
            <td style="width: 10px;"></td>
            <td>
                @Html.LabelFor(model => model.effective_to)
            </td>
            <td>
                @Html.EditorFor(model => model.effective_to)<br />
                @Html.ValidationMessageFor(model => model.effective_to)
            </td>
        </tr>
        
        <tr>
            <td>
                <label> Grades </label><br />
                @Html.ValidationMessageFor(model => model.Grades)
            </td>
            <td colspan="4">
                <ul style="margin-left: 0;">
                    @foreach (var g in Model.Grades)
                    {
                        <li style="display: inline;">
                            @Html.Hidden("Grades.Index", g.id)
                            @Html.Hidden(string.Format("Grades[{0}].id", @g.id), @g.id)
                            @Html.Hidden(string.Format("Grades[{0}].grade", @g.id), @g.grade)
                            @Html.Hidden(string.Format("Grades[{0}].IsSelected", @g.IsSelected), @g.grade)
                            @Html.CheckBox(string.Format("Grades[{0}].IsSelected", @g.id), @g.IsSelected, new { @style = "padding-right:5px;" })  @Html.Label(@g.grade, new { @style = "padding-right:20px;" }) 
                        </li>
                    }
               </ul>
            </td>
        </tr>
        <tr>
            <td> @Html.LabelFor(model => model.confirmed_emp)</td>
            <td >
                @Html.DropDownListFor(model => model.confirmed_emp, new SelectList(EnumToSelectItemList.GetEnumSelectList<ConfirmedEmployee>(), "Text", "Text"))
            </td>
            <td style="width: 10px;"></td>
            <td> @Html.LabelFor(model => model.is_taxable)</td>
            <td colspan="4">
                @Html.DropDownListFor(model => model.is_taxable, new SelectList(EnumToSelectItemList.GetEnumSelectList<IsTaxable>(), "Text", "Text"))
            </td>
        </tr>
        <tr>
            
        </tr>
        <tr>
            <td> @Html.LabelFor(model => model.gender_dependant)</td>
            <td colspan="4">
                @Html.DropDownListFor(model => model.gender_dependant, new SelectList(EnumToSelectItemList.GetEnumSelectList<Genders>(), "Text", "Text"))
            </td>
        </tr>
        <tr>
            <td style="color:green">
                Applied As:
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.flat_amount)
            </td>
            <td>
                @Html.TextBoxFor(model => model.flat_amount)<br/>
                @Html.ValidationMessageFor(model => model.flat_amount)
            </td>
            <td style="width: 10px;"></td>
            <td>
                @Html.LabelFor(model => model.percentage_of_basic)
            </td>
            <td>
                @Html.TextBoxFor(model => model.percentage_of_basic)<br/>
                @Html.ValidationMessageFor(model => model.percentage_of_basic)
            </td>
        </tr>
       @* <tr>
            <td>
                @Html.LabelFor(model => model.number_of_basic)
            </td>
            <td>
                @Html.TextBoxFor(model => model.number_of_basic)<br/>
                @Html.ValidationMessageFor(model => model.number_of_basic)
            </td>
            <td style="width: 10px;"></td>
            <td>
                @Html.LabelFor(model => model.basic_of_days)
            </td>
            <td>
                @Html.TextBoxFor(model => model.basic_of_days)<br/>
                @Html.ValidationMessageFor(model => model.basic_of_days)
            </td>
        </tr>*@
        
    </table>

    <p>
        <input class="btn btn-success" type="submit" value="Create" />
    </p>
   
}

<div>
    @Html.ActionLink("Back to List", "ConfigureBonus")
</div>

@section PageSpecificJs
{
    <script type="text/javascript" src="~/Scripts/bootstrap-datepicker.js"></script>
    <script type="text/javascript">
        $('#effective_from,#effective_to').datepicker({ dateFormat: 'yy-mm-dd' });


        $('#percentage_of_basic').on("click", function () {
            $('#flat_amount').val('');
        });

        $('#flat_amount').on("click", function () {
            $('#percentage_of_basic').val('');
        });

        $('#bonus_name_id').change(function () {
            var ks = $('#bonus_name_id option:selected').val();
            var test = '@Url.Action("ConfigureBonus", "Bonus", new { bonusId = "PLACEHOLDER" })';
            var myUrl = test.replace('PLACEHOLDER', ks);
            document.location.href = myUrl;
        });

    </script>

}

Project-GPIT-Payroll/PayrollWeb/Views/Bonus/DisburseBonus.cshtml
@using System.Diagnostics.Eventing.Reader
@using PayrollWeb.Models
@using PayrollWeb.ViewModels
@model PayrollWeb.ViewModels.BonusProcess

@{
    ViewBag.Title = "DisburseBonus";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}

@section PageBanner
{
    Disburse Bonus
}

<br style="clear: both;"/>
    @{
        if (TempData.ContainsKey("msg"))
        {
            var res = (OperationResult)TempData["msg"];
            if (res.IsSuccessful)
            {
                <div id="notifyUser" class="alert alert-success">
			    <button data-dismiss="alert" class="close" type="button">×</button>
			    <div>@res.Message </div>
                </div>    
            }
            else
            {
                <div id="notifyUser" class="alert alert-error">
			    <button data-dismiss="alert" class="close" type="button">×</button>
			    <div>@res.Message </div>
                </div> 
            }
        }
    }

@using (Html.BeginForm("DisburseBonus", "Bonus", FormMethod.Post, new { @class = "form-inline" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.id)
    
        <table class="table">
         <tr>
             <td> @Html.LabelFor(model=>model.festival_date)</td>
            <td >
                @Html.EditorFor(model => model.festival_date)<br />
                @Html.ValidationMessageFor(model => model.festival_date)
            </td>
         </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.bonus_name_id)
            </td>
            <td>
               @Html.DropDownListFor(model => model.bonus_name_id, new SelectList(@ViewBag.BonusNames, "id", "name", @ViewBag.SelectedIndex), "---- Select ----") <br />
               @Html.ValidationMessageFor(model => model.bonus_name_id) 
            </td>
        </tr>
        <tr>
            <td> @Html.LabelFor(model=>model.batch_no)</td>
            <td >
                @Html.TextBoxFor(model => model.batch_no, new { @readonly = "readonly" })
            </td>
        </tr>
    </table>
   
     <p>
        <input class="btn btn-success" type="submit" value="Disburse" onclick = "BonusDisbursement(this); return false;" />
    </p>
   
}

<div id="dltBonus" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-body">
    <p>Are you sure you want to disburse bonus?</p>
    </div>
    <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button id="btnDltBonus" class="btn btn-primary">Disburse</button>
    </div>
</div>

@section PageSpecificJs
{
    <script type="text/javascript" src="~/Scripts/bootstrap-datepicker.js"></script>
    <script type="text/javascript">
        $('#festival_date').datepicker({ dateFormat: 'yy-mm-dd' });

        $('#bonus_name_id').change(function () {
            var ks = $('#bonus_name_id option:selected').val();
            var fd = $('#festival_date').val();
            var _param2 = ks.toString() + "T" + fd.toString();
            var test = '@Url.Action("DisburseBonus","Bonus",new{_param = "PLACEHOLDER"  })';
            var myUrl = test.replace('PLACEHOLDER', _param2.toString());
            document.location.href = myUrl;
        });

    </script>

    <script type="text/javascript">
        function BonusDisbursement(el) {
            $('#dltBonus').modal('show');

            $('#btnDltBonus').click(function () {
                $('#dltBonus').modal('hide');
                var test = $(el).attr('href');
                document.forms[0].submit();
            });
        }
    </script>

}