Project-GPIT-Payroll/PayrollWeb/Controllers/SetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using com.gpit.DataContext;
using AutoMapper;
using com.gpit.Model;
using Ninject.Infrastructure.Language;
using PayrollWeb.ViewModels;
using System.Web.Security;
using PayrollWeb.Utility;

namespace PayrollWeb.Controllers
{
    public class SetupController : Controller
    {
        //
        // GET: /Setup/
        private readonly payroll_systemContext dataContext;

        public SetupController(payroll_systemContext context)
        {
            this.dataContext = context;
        }

        public ActionResult Index()
        {
            return View();
        }


        //public PartialViewResult GetMenuForUser()
        //{
        //    var model = _securityLayer.GetUrlForUser(HttpContext.User.Identity.Name);

        //    return PartialView("_UserMenu", model);
        //}

        public ActionResult CreateEmployee()
        {
            var ev = new EmployeeView();
            ev.account_no = "786";
            
            return View(ev);
        }

        [HttpGet]
        public ActionResult CreateDivision()
        {
            var ev = new Division();
            return View(ev);
        }
        [HttpPost]
        public ActionResult CreateDivision(Division d)
        {
            if(ModelState.IsValid)
            {
                var ev = new prl_division();
                ev.name = d.name;

                dataContext.prl_division.Add(ev);
                dataContext.SaveChanges();
                return RedirectToAction("CreateEmployee");
            }
            return View();
        }
        [HttpGet]
        public ActionResult CreateDepartment()
        {
            Department dp = new Department();
            return View(dp);
        }
        [HttpPost]
        public ActionResult CreateDepartment(Department d)
        {
            if (ModelState.IsValid)
            {
                var ev = new prl_department();
                ev.name = d.name;
                ev.created_by = "test";
                ev.created_date = DateTime.Now;

                dataContext.prl_department.Add(ev);
                dataContext.SaveChanges();
                return RedirectToAction("CreateEmployee");
            }
            return View();
        }
    }
}

Project-GPIT-Payroll/PayrollWeb/Views/Setup/CreateBank.cshtml
@using System.Web.Mvc.Html
@using System.Web.UI.WebControls
@using PayrollWeb.ViewModels


@{
    ViewBag.Title = "CreateBank";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}

@Html.Partial("_EditBank",(Bank)ViewBag.bank)

Project-GPIT-Payroll/PayrollWeb/Views/Setup/CreateDepartment.cshtml
@model PayrollWeb.ViewModels.Department

@{
    ViewBag.Title = "CreateDepartment";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}

@using (Html.BeginForm("CreateDepartment", "Setup", FormMethod.Post))
{
    <fieldset>
        <legend>Department info</legend>
        
        <table>
            <tr>
                <td></td>
                <td>
                    @Html.ValidationSummary(false)
                </td>

            </tr>
            <tr>
                <td>@Html.LabelFor(x=>x.name)</td>
                <td>@Html.EditorFor(x => x.name)</td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input class="btn btn-success" type="submit" value="Save"/>
                </td>
            </tr>
        </table>
    </fieldset>
}

Project-GPIT-Payroll/PayrollWeb/Views/Setup/CreateDivision.cshtml
@model PayrollWeb.ViewModels.Division

@{
    ViewBag.Title = "CreateDivision";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}

@using(Html.BeginForm("CreateDivision","Setup",FormMethod.Post)){
    <fieldset>
        <legend>Division info</legend>
        
        <table>
            <tr>
                <td></td>
                <td>
                    @Html.ValidationSummary(false)
                </td>

            </tr>
            <tr>
                <td>@Html.LabelFor(x=>x.name)</td>
                <td>@Html.EditorFor(x => x.name)</td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input class="btn btn-success" type="submit" value="Save"/>
                </td>
            </tr>
        </table>
    </fieldset>
}

Project-GPIT-Payroll/PayrollWeb/Views/Setup/CreateEmployee.cshtml
@model PayrollWeb.ViewModels.EmployeeView

@{
    ViewBag.Title = "CreateEmployee";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}

@using (Html.BeginForm())
{
    
    <fieldset>
        <legend>Employee info</legend>
        <table>
            <tr>
                <td>@Html.LabelFor(x=>x.name)</td>
                <td>@Html.EditorFor(x => x.name)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(x=>x.present_address)</td>
                <td>@Html.EditorFor(x => x.present_address)   </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(x=>x.permanent_address)</td>
                <td>@Html.EditorFor(x => x.permanent_address)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(x=>x.phone)</td>
                <td>@Html.EditorFor(x => x.phone)</td>
            </tr>
            <tr>
                <td> @Html.LabelFor(x=>x.email)</td>
                <td>@Html.EditorFor(x => x.email)</td>
            </tr>
            <tr>
                <td>Gender</td>
                <td>
                    @foreach (var g in Model.Genders)
                    {
                        @Html.RadioButtonFor(x=>x.gender,@g) @g.Text
                    }
                </td>
            </tr>
           
        </table>
    </fieldset>
    
}

Project-GPIT-Payroll/PayrollWeb/Views/Setup/Index.cshtml
@using System.Web.Mvc.Html
@using MvcSiteMapProvider
@using MvcSiteMapProvider.Web.Html.Models

@model List<PayrollWeb.ViewModels.SubMenu>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}

@section PageBanner
{
    Setup Home Page
}