Project-GPIT-Payroll/PayrollWeb/ViewModels/Company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PayrollWeb.ViewModels
{
    public class Company
    {
        [HiddenInput(DisplayValue=true)]
        public int id { get; set; }

        [Required(ErrorMessage = "Company name can not be empty.")]
        [DisplayName("Company Name ")]
        public string name { get; set; }
        [DisplayName("Description ")]
        public string description { get; set; }
        [DisplayName("Address ")]
        public string address { get; set; }

        [DisplayName("Primary Phone ")]
        public string primary_phone { get; set; }
        [DisplayName("Secondary Phone ")]
        public string secondary_phone { get; set; }

        [DisplayName("Email Address ")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",ErrorMessage="Please enter a valid email address.")]
        public string email { get; set; }

        [DisplayName("Web Address ")]
        public string web { get; set; }

        [DisplayName("Company Logo ")]
        public string logo { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}

Project-GPIT-Payroll/PayrollWeb/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AutoMapper;
using com.gpit.DataContext;
using com.gpit.Model;
using PayrollWeb.CustomSecurity;
using PayrollWeb.Utility;
using PayrollWeb.ViewModels;

namespace PayrollWeb.Controllers
{
    public class CompanyController : Controller
    {
        private readonly payroll_systemContext dataContext;

        public CompanyController(payroll_systemContext cont)
        {
            this.dataContext = cont;
        }

        public ActionResult Index()
        {

            var lstCompanies = dataContext.prl_company.ToList().OrderBy(p=>p.name);
            return View(Mapper.Map<List<Company>>(lstCompanies));
        }

        [PayrollAuthorize]
        public ActionResult Details(int id)
        {
            var lstCom = dataContext.prl_company.SingleOrDefault(x => x.id == id);
            return View(Mapper.Map<Company>(lstCom));
        }

        public ActionResult Create()
        {
            Company _Company = new Company();
            return View(_Company);
        }

        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Logo")]Company comp, HttpPostedFileBase Logo)
        {
            var res = new OperationResult();
            try
            {
                if (ModelState.IsValid)
                {
                    var _comp = new prl_company();
                    if (Logo != null && Logo.ContentLength > 0)
                    {
                        var logoName = Path.GetFileName(Logo.FileName);
                        if (System.IO.File.Exists(Server.MapPath("~/Images/CompanyLogo/"+logoName)))
                        {
                            logoName = 1+logoName;
                        }
                        var path = Path.Combine(Server.MapPath("~/Images/CompanyLogo"), logoName);
                        Logo.SaveAs(path);
                        _comp.logo = logoName;
                    }
                    _comp.name = comp.name;
                    _comp.description = comp.description;
                    _comp.address = comp.address;
                    _comp.primary_phone = comp.primary_phone;
                    _comp.secondary_phone = comp.secondary_phone;
                    _comp.email = comp.email;
                    _comp.web = comp.web;
                    _comp.created_by = User.Identity.Name;
                    _comp.created_date = DateTime.Now;

                    dataContext.prl_company.Add(_comp);
                    dataContext.SaveChanges();

                    res.IsSuccessful = true;
                    res.Message = "Company named " + comp.name + " created successfully.";
                    TempData.Add("msg", res);

                    return RedirectToAction("Index");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        

        public ActionResult Edit(int id)
        {
            var _company = dataContext.prl_company.SingleOrDefault(x => x.id == id);
            return View(Mapper.Map<Company>(_company));
        }

        [HttpPost]
        public ActionResult Edit(int id,Company comp, HttpPostedFileBase cLogo)
        {
            var res = new OperationResult();
            try
            {
                if (ModelState.IsValid)
                {
                    var editCompany = dataContext.prl_company.SingleOrDefault(x => x.id == comp.id);

                    if (cLogo != null && cLogo.ContentLength > 0)
                    {
                        if (editCompany.logo != null)
                        {
                            System.IO.File.Delete(Server.MapPath("~/Images/CompanyLogo/" + editCompany.logo));
                        }
                        var logoName = Path.GetFileName(cLogo.FileName);
                        if (System.IO.File.Exists(Server.MapPath("~/Images/CompanyLogo/" + logoName)))
                        {
                            logoName = 1+logoName;
                        }
                        var path = Path.Combine(Server.MapPath("~/Images/CompanyLogo"), logoName);
                        cLogo.SaveAs(path);
                        editCompany.logo = logoName;
                    }
                    editCompany.name = comp.name;
                    editCompany.description = comp.description;
                    editCompany.address = comp.address;
                    editCompany.primary_phone = comp.primary_phone;
                    editCompany.secondary_phone = comp.secondary_phone;
                    editCompany.email = comp.email;
                    editCompany.web = comp.web;
                    editCompany.updated_by = User.Identity.Name;
                    editCompany.updated_date = DateTime.Now;

                    res.IsSuccessful = true;
                    res.Message = "Information of " + editCompany.name + " updated successfully.";
                    TempData.Add("msg", res);

                    dataContext.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                
            }

            return View();
        }

        
        public ActionResult Delete(int id)
        {
            string name = "";
            string logo = "";
            var res = new OperationResult();
            try
            {
                var theData = dataContext.prl_company.SingleOrDefault(x => x.id == id);
                if (theData == null)
                {
                    return HttpNotFound();
                }
                name = theData.name;
                logo = theData.logo;

                dataContext.prl_company.Remove(theData);
                dataContext.SaveChanges();

                System.IO.File.Delete(Server.MapPath("~/Images/CompanyLogo/" + logo));

                res.IsSuccessful = true;
                res.Message = name + " deleted successfully.";
                TempData.Add("msg", res);
            }
            catch (Exception ex)
            {
                res.IsSuccessful = false;
                res.Message = name + " could not delete.";
                TempData.Add("msg", res);
            }

            return RedirectToAction("Index");
        }
    }
}

Project-GPIT-Payroll/PayrollWeb/Views/Company/Create.cshtml
@model PayrollWeb.ViewModels.Company

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}
@section PageBanner
{
    Create Company
}


@using (Html.BeginForm("Create", "Company", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="span3">
            @Html.EditorFor(model => model.name)
        </div>
        <div class="span4 offset1">
            @Html.ValidationMessageFor(model => model.name)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.description)
        </div>
        <div class="span3">
            @Html.EditorFor(model => model.description)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.address)
        </div>
        <div class="span3">
            @Html.TextAreaFor(model => model.address)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.primary_phone)
        </div>
        <div class="span3">
            @Html.EditorFor(model => model.primary_phone)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.secondary_phone)
        </div>
        <div class="span3">
            @Html.EditorFor(model => model.primary_phone)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.email)
        </div>
        <div class="span3">
            @Html.EditorFor(model => model.email)
        </div>
        <div class="span4 offset1">
            @Html.ValidationMessageFor(model => model.email)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.web)
        </div>
        <div class="span3">
            @Html.EditorFor(model => model.web)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.logo)
        </div>
        <div class="span3">
            <input type="file" name="Logo" id="Logo" />
        </div>
    </div>
    <br />
    <div class="row-fluid">
        <div class="span2">
            
        </div>
        <div class="span3">
            <table>
                <tr>
                    <td>
                        <input class="btn btn-success" type="submit" value="Create" />
                    </td>
                    <td style="width:20px"></td>
                    <td>
                        @Html.ActionLink("Back to List", "Index")
                    </td>
                </tr>
            </table>
        </div>
    </div>
}

Project-GPIT-Payroll/PayrollWeb/Views/Company/Details.cshtml
@model PayrollWeb.ViewModels.Company
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}
@section PageBanner
{
    Company Details
}

@Html.MvcSiteMap().SiteMapPath()

<table style="border-collapse: separate; border-spacing: 5px;">
    <tr>
        <td style="text-align:right">
            @Html.DisplayNameFor(model => model.name)
        </td>
        <td style="width: 30px"></td>
        <td style=" text-align:left; font-weight: bolder">
            @Html.DisplayFor(model => model.name)
        </td>
        <td style="width: 120px"></td>
        <td style="text-align:right">
            @Html.DisplayNameFor(model => model.address)
        </td>
        <td style="width: 30px"></td>
        <td style=" text-align:left; font-weight: bolder">
            @Html.DisplayFor(model => model.address)
        </td>
    </tr>
    <tr>
        <td style="text-align:right">
            @Html.DisplayNameFor(model => model.primary_phone)
        </td>
        <td style="width: 30px"></td>
        <td style=" text-align:left; font-weight: bolder">
            @Html.DisplayFor(model => model.primary_phone)
        </td>
        <td style="width: 120px"></td>
        <td style="text-align:right">
            @Html.DisplayNameFor(model => model.secondary_phone)
        </td>
        <td style="width: 30px"></td>
        <td style=" text-align:left; font-weight: bolder">
            @Html.DisplayFor(model => model.secondary_phone)
        </td>
    </tr>
    <tr>
        <td style="text-align:right">
            @Html.DisplayNameFor(model => model.email)
        </td>
        <td style="width: 30px"></td>
        <td style=" text-align:left; font-weight: bolder">
            @Html.DisplayFor(model => model.email)
        </td>
        <td style="width: 120px"></td>
        <td style="text-align:right">
            @Html.DisplayNameFor(model => model.web)
        </td>
        <td style="width: 30px"></td>
        <td style=" text-align:left; font-weight: bolder">
            @Html.DisplayFor(model => model.web)
        </td>
    </tr>
    <tr>
        <td style="text-align:right">
            @Html.DisplayNameFor(model => model.description)
        </td>
        <td style="width: 30px"></td>
        <td style=" text-align:left; font-weight: bolder">
            @Html.DisplayFor(model => model.description)
        </td>
        <td style="width: 120px"></td>
        <td style="text-align:right">
            @Html.DisplayNameFor(model => model.logo)
        </td>
        <td style="width: 30px"></td>
        <td style=" text-align:left; font-weight: bolder">
            <img src="@Url.Content("~/Images/CompanyLogo/" + Model.logo)" />
        </td>
    </tr>
    <tr>
        <td colspan="7" style="height: 20px"></td>
    </tr>
    <tr>
        <td colspan="7" style="text-align: right">
            @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
            @Html.ActionLink("Back to List", "Index")
        </td>
    </tr>
</table>

Project-GPIT-Payroll/PayrollWeb/Views/Company/Edit.cshtml
@model PayrollWeb.ViewModels.Company

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}
@section PageBanner
{
Edit Company
}

@using (Html.BeginForm("Edit", "Company", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    @Html.HiddenFor(model => model.id)

    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="span3">
            @Html.EditorFor(model => model.name)
        </div>
        <div class="span4 offset1">
            @Html.ValidationMessageFor(model => model.name)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.description)
        </div>
        <div class="span3">
            @Html.EditorFor(model => model.description)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.address)
        </div>
        <div class="span3">
            @Html.TextAreaFor(model => model.address)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.primary_phone)
        </div>
        <div class="span3">
            @Html.EditorFor(model => model.primary_phone)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.secondary_phone)
        </div>
        <div class="span3">
            @Html.EditorFor(model => model.primary_phone)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.email)
        </div>
        <div class="span3">
            @Html.EditorFor(model => model.email)
        </div>
        <div class="span4 offset1">
            @Html.ValidationMessageFor(model => model.email)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.web)
        </div>
        <div class="span3">
            @Html.EditorFor(model => model.web)
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            @Html.LabelFor(model => model.logo)
        </div>
        <div class="span3">
            <img src="@Url.Content("~/Images/CompanyLogo/" + Model.logo)" />
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
        </div>
        <div class="span3">
            <input type="file" name="cLogo" id="cLogo" />
        </div>
    </div>
    <br />
    <div class="row-fluid">
        <div class="span2">
        </div>
        <div class="span3">
            <table>
                <tr>
                    <td>
                        <input class="btn btn-success" type="submit" value="Update" />
                    </td>
                    <td style="width: 20px"></td>
                    <td>
                        @Html.ActionLink("Back to List", "Index")
                    </td>
                </tr>
            </table>
        </div>
    </div>
}

Project-GPIT-Payroll/PayrollWeb/Views/Company/Index.cshtml
@using PayrollWeb.ViewModels
@model List<PayrollWeb.ViewModels.Company>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutDetailsPage.cshtml";
}
@section PageBanner
{
    Company
}



<div class="" style="float: right; margin-bottom: 10px;">
    <a class="btn btn-primary" href="@Url.Action("Create")"><i class="icon-plus"></i>Create New </a>
</div>
<br style="clear: both;" />

@{
    if (TempData.ContainsKey("msg"))
    {
        var res = (OperationResult)TempData["msg"];
        if (res.IsSuccessful)
        {
        <div id="notifyUser" class="alert alert-success">
            <button data-dismiss="alert" class="close" type="button">×</button>
            <div>@res.Message </div>
        </div>    
        }
        else
        {
        <div id="notifyUser2" class="alert alert-error">
            <button data-dismiss="alert" class="close" type="button">×</button>
            <div>@res.Message </div>
        </div> 
        }
    }
}

<table class="table table-striped">
    <tr>
        <th>Name</th>
        <th>Phone No.</th>
        <th>Email</th>
        <th>Web</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.primary_phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.web)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Company", new { id = item.id }, null)
                @Html.ActionLink("Details", "Details", "Company", new { id = item.id }, null)
                @Html.ActionLink("Delete", "Delete", "Company", new { id = item.id }, new { onclick = "DeleteFunc(this);return false;" })
            </td>
        </tr>
    }

</table>

<div id="dlt" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-body">
    <p>Are you sure you want to delete this company?</p>
    </div>
    <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button id="btnDlt" class="btn btn-primary">Delete</button>
    </div>
</div>
@section PageSpecificJs
{
    <script type="text/javascript">
        function DeleteFunc(el)
        {
            $('#dlt').modal('show');

            $('#btnDlt').click(function () {
                $('#dlt').modal('hide');
                var test = $(el).attr('href');
                document.location.href = test;
            });
        }
    </script>
}